### ISSUE TITLE
topic suggestion - use of {{ with (index .Site.Data (.Get "src")) }}

### ISSUE THREAD

**Issue by Carpintonto** [Ypertex/blog#10]
Yours is [the only example of how to pass a static data file to a template with an inline shortcode](https://blog.ypertex.com/articles/useful-hugo-templating/) that I have found.

I'm not finding any discussion of "with (index" usage.

I'm brand new to hugo and don't know what I'm looking for is very likely the case - thanks.

**Comment by MichaelSchmidle** [comment]
Hi @Carpintonto, thanks for opening the issue and suggesting a topic.

However, I'm not quite sure what exactly you're suggesting. What part is it that you would like to learn/understand better?

The index function is explained in [Hugo's docs](https://gohugo.io/functions/index-function/) if that's what you're looking for... Otherwise, please explain a bit more. Thanks and regards!

**Comment by Carpintonto** [comment]
thank you Michael.

I thought I was looking for a statement.
Now with the knowledge that "where" and "index" are functions I can proceed.

I might have been looking at other snippets that do the same thing but

{{ with (index .Site.Data (.Get "src")) }}

is syntax I understand.

I was getting impatient with the very basic examples at gohugo.io
that seemed to suggest every data source would require its own template.

Thanks for the pointer!

**Comment by MichaelSchmidle** [comment]
You're welcome! Glad that I could be of help.
